# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:55
from __future__ import unicode_literals
from django.db import migrations
from movieratings.models import Rater


def read_data(*args):
    with open("/Users/jtwitty/PycharmProjects/twitty_movies/movieratings/migrations/u.user") as users:
        for user in users.readlines():
            line = user.split("|")
            Rater.objects.create(
                id=line[0],
                age=line[1],
                gender=line[2],
                occupation=line[3],
                zip_code=line[4]
            )



class Migration(migrations.Migration):


    dependencies = [
        ('movieratings', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(read_data)
    ]