# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 15:27
from __future__ import unicode_literals

from django.db import migrations

from movieratings.models import Review, Rater, Movie


def load_review_data(*args):
   with open("/Users/jtwitty/PycharmProjects/twitty_movies/movieratings/migrations/u.data") as reviews:
       for review in reviews.readlines():
           line = review.split('\t')
           Review.objects.create(reviewer=Rater(line[0]), movie=Movie(line[1]), rating=line[2])

class Migration(migrations.Migration):

   dependencies = [
       ('movieratings', '0003_auto_20160226_1501'),
   ]

   operations = [
       migrations.RunPython(load_review_data)
   ]