# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0004_auto_20160226_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rater',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10),
        ),
    ]
