# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Avg


from movieratings.models import Review, Movie


def averages(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    Review = apps.get_model('movieratings', 'Review')
    for item in Movie.objects.all():
        averages = Review.objects.filter(movie=item).aggregate(Avg('rating'))
        item.avg_rating = averages['rating__avg']
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0005_auto_20160227_1632'),
    ]

    operations = [
                migrations.RunPython(averages)

    ]
